export const actions = {
  profile: {
    DATA_FETCHNG: "PROFILE_DATA_FETCHING",
    DATA_FETCHED: "PROFILE_DATA_FETCHED",
    DATA_FETCH_ERROR: "PROFILE_DATA_FETCH_ERROR",
    USER_DATA_EDITED: "PROPILE_USER_DATA_EDITED",
    IMAGE_UPDATED: "PROFILE_IMAGE_UPDATED",
  },
  post: {
    DATA_FETCHNG: "POST_DATA_FETCHING",
    DATA_FETCHED: "POST_DATA_FETCHED",
    DATA_FETCH_ERROR: "POST_DATA_FETCH_ERROR",
    DATA_CREATED: "POST_DATA_CREATED",
    DATA_EDITED: "POST_DATA_EDITED",
    POST_DELETED: "POST_DATA_DELETED",
  },
};
